### PR TITLE
Add Examples section (appendix)

### PR DESCRIPTION
**Pull request by geonnave**
Addresses #6.

### CODE REVIEW

**Comment by geonnave** [comment]
Note that the second example (equivalent to UC4 in #6) does not include the `hint`, as it is not specified yet. It can be added back once that is done.

**Comment by geonnave** [comment]
@gselander I added more details to the examples, do you want to take a look?

**Comment by gselander** [comment]
Looks good, but I didn't understand this:

> the access policy in W specifies, via a list of ID_U, that device u1 can enroll via any domain authenticator, i.e., the list is: \[14\]

How can I understand that the list has this format?

**Comment by gselander** [comment]
Comparing with this in the second example. 

> {14, 39-63-C9-D0-5C-62}

The brackets are confusing, but is the absence of other entries (besides 14) in the previous example an indication that there is no restriction on what gateway?

**Comment by geonnave** [comment]
> How can I understand that the list has this format?

My goal is just to provide an example of how the access policy could look like at W, while its exact format is out of scope (it is up to the authorization mechanism to define that).

Maybe I could change it to `e.g., the access policy could look like this: [14]` (note the use of `e.g.` instead of `i.e.`) to make it clear that it is just an example.

**Comment by geonnave** [comment]
> The brackets are confusing, but is the absence of other entries (besides 14) in the previous example an indication that there is no restriction on what gateway?

Yes, I intend for one example to have no restriction on the gateway, and another to have such restriction. The bracket notation is supposed to denote a mapping of ID_U and MAC Addresses, I can think of something else if that is not clear.

**Comment by gselander** [comment]
> Yes, I intend for one example to have no restriction on the gateway, and another to have such restriction. The bracket notation is supposed to denote a mapping of ID_U and MAC Addresses, I can think of something else if that is not clear.

Yes, please change from "i.e." to "e.g.", the former gives the impression that there is something that should be understood based on something else. The examples are fine. It would be good with a common notation was used in both examples, and perhaps also the asymmetry between the first element and the following element(s), for example (14; MAC1, MAC2, ...)  and (14; ). Or (14; *).

**Comment by geonnave** [comment]
I re-arranged the text so that there is no "expectation" on formats that are not defined. In doing so I decided to keep `i.e.`, because using `e.g.` again within the example felt redundant.

In summary, the changes are:
1. in the first example, I abstracted away the format of the policy
2. in the second one, I defined the policy format, so that I could use `i.e.` to mean a clear implication

**Review by gselander — APPROVED** [review]

**Pull request merged**
